### PR TITLE
Migrate to nom 5 and function parsers

### PR DESCRIPTION
**Pull request by fparat**
Hi,

This is a pull request for updating the dependencies.
In particular, nom is migrated from version 3.2.1 to 5 and this introduced many breaking changes.

This PR is composed of 3 commits:

1. the first updates the toml file, and does the minimal changes in code for making the tests pass.
2. the second migrates all the macro-based parsers to function-based parsers.
3. the last optimizes the code for fixing a performance regression.

### CODE REVIEW

**Comment by Dushistov** [comment]
Thanks, @fparat . I will look at it and fix CI issues after end of vacation next week.

**Comment by fparat** [comment]
It seems the failure is caused by `getrandom`, an indirect dependency of `quickcheck` that requires rust 1.32.
I see two solutions, increasing the minimum version of rust to 1.32, or reverting the version of `quickcheck` to 0.7. You can decide what to do after your vacation.

**Comment by Dushistov** [comment]
@fparat , thank you for PR.

**Comment by fparat** [comment]
Thanks for merging!

**Pull request merged**
